#!/usr/bin/env python3
"""
Add closed-model entries for Anthropic, Google DeepMind, and OpenAI
with techReport URLs from official model card pages.

Run: python scripts/add_oag_model_cards.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
MODELS_FILE = ROOT / "data" / "models.json"

# ── New entries ────────────────────────────────────────────────────────────────
# Convention for closed models:
#   - id: "{org-slug}/{model-slug}"
#   - huggingfaceUrl: omitted
#   - techReport: official model card / system card URL
#   - parameterConfidence: "official" | "reported" | "rumored" (or omit if unknown)
#   - totalParameters / activeParameters: null if not disclosed

NEW_ENTRIES = [

    # ── Anthropic ──────────────────────────────────────────────────────────────
    {
        "id": "anthropic/claude-2",
        "name": "Claude 2",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/bd2a28d2535bfb0494cc8e2a3bf135d2e7523226/Model-Card-Claude-2.pdf",
        "contextLength": 100000,
        "architecture": "claude",
        "inputModalities": ["text"],
        "outputModalities": ["text"],
        "releasedAt": "2023-07-11T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-2.1",
        "name": "Claude 2.1",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/bd2a28d2535bfb0494cc8e2a3bf135d2e7523226/Model-Card-Claude-2.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text"],
        "outputModalities": ["text"],
        "releasedAt": "2023-11-21T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-3-haiku",
        "name": "Claude 3 Haiku",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/c6a80a657af445f40e31afac050f3bf76d3b1404.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2024-03-13T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-3-sonnet",
        "name": "Claude 3 Sonnet",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/c6a80a657af445f40e31afac050f3bf76d3b1404.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2024-03-04T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-3-opus",
        "name": "Claude 3 Opus",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/c6a80a657af445f40e31afac050f3bf76d3b1404.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2024-03-04T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-3.5-sonnet",
        "name": "Claude 3.5 Sonnet",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/fed9cc193a14b84131812372d8d5857f8f304c52/Model_Card_Claude_3_Addendum.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2024-06-20T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-3.5-sonnet-v2",
        "name": "Claude 3.5 Sonnet v2",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/c7822cdc35ad788ec87e14b3a9d45010f1f86c38.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2024-10-22T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-3.5-haiku",
        "name": "Claude 3.5 Haiku",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/c7822cdc35ad788ec87e14b3a9d45010f1f86c38.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2024-11-04T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-3.7-sonnet",
        "name": "Claude 3.7 Sonnet",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/9ff93dfa8f445c932415d335c88852ef47f1201e.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-02-24T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-sonnet-4",
        "name": "Claude Sonnet 4",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/07b2a3f9902ee19fe39a36ca638e5ae987bc64dd.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-05-22T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-opus-4",
        "name": "Claude Opus 4",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/07b2a3f9902ee19fe39a36ca638e5ae987bc64dd.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-05-22T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-opus-4.1",
        "name": "Claude Opus 4.1",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/9fa30625273bafdf5af82c93719d7ca606485a16.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-08-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-sonnet-4.5",
        "name": "Claude Sonnet 4.5",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/963373e433e489a87a10c823c52a0a013e9172dd.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-09-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-haiku-4.5",
        "name": "Claude Haiku 4.5",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/7aad69bf12627d42234e01ee7c36305dc2f6a970.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-10-22T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-opus-4.5",
        "name": "Claude Opus 4.5",
        "provider": "Anthropic",
        "techReport": "https://www-cdn.anthropic.com/bf10f64990cfda0ba858290be7b8cc6317685f47.pdf",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-11-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-sonnet-4.6",
        "name": "Claude Sonnet 4.6",
        "provider": "Anthropic",
        "techReport": "https://anthropic.com/claude-sonnet-4-6-system-card",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2026-02-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-opus-4.6",
        "name": "Claude Opus 4.6",
        "provider": "Anthropic",
        "techReport": "https://anthropic.com/claude-opus-4-6-system-card",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2026-02-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-opus-4.7",
        "name": "Claude Opus 4.7",
        "provider": "Anthropic",
        "techReport": "https://anthropic.com/claude-opus-4-7-system-card",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2026-04-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },
    {
        "id": "anthropic/claude-mythos-preview",
        "name": "Claude Mythos Preview",
        "provider": "Anthropic",
        "techReport": "https://www.anthropic.com/claude-mythos-preview-system-card",
        "contextLength": 200000,
        "architecture": "claude",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2026-04-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Claude",
    },

    # ── Google DeepMind — Gemini (closed, API-only) ────────────────────────────
    {
        "id": "google/gemini-2.0-flash",
        "name": "Gemini 2.0 Flash",
        "provider": "Google DeepMind",
        "techReport": "https://deepmind.google/models/model-cards/gemini-2-0-flash/",
        "contextLength": 1048576,
        "architecture": "gemini",
        "inputModalities": ["text", "image", "audio", "video"],
        "outputModalities": ["text", "image", "audio"],
        "releasedAt": "2025-02-05T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Gemini",
    },
    {
        "id": "google/gemini-2.0-flash-lite",
        "name": "Gemini 2.0 Flash-Lite",
        "provider": "Google DeepMind",
        "techReport": "https://deepmind.google/models/model-cards/gemini-2-0-flash-lite/",
        "contextLength": 1048576,
        "architecture": "gemini",
        "inputModalities": ["text", "image", "audio", "video"],
        "outputModalities": ["text"],
        "releasedAt": "2025-02-05T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Gemini",
    },
    {
        "id": "google/gemini-2.5-flash",
        "name": "Gemini 2.5 Flash",
        "provider": "Google DeepMind",
        "techReport": "https://deepmind.google/models/model-cards/gemini-2-5-flash/",
        "contextLength": 1048576,
        "architecture": "gemini",
        "inputModalities": ["text", "image", "audio", "video"],
        "outputModalities": ["text"],
        "releasedAt": "2025-05-20T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Gemini",
    },
    {
        "id": "google/gemini-2.5-flash-lite",
        "name": "Gemini 2.5 Flash-Lite",
        "provider": "Google DeepMind",
        "techReport": "https://deepmind.google/models/model-cards/gemini-2-5-flash-lite/",
        "contextLength": 1048576,
        "architecture": "gemini",
        "inputModalities": ["text", "image", "audio", "video"],
        "outputModalities": ["text"],
        "releasedAt": "2025-06-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Gemini",
    },
    {
        "id": "google/gemini-2.5-pro",
        "name": "Gemini 2.5 Pro",
        "provider": "Google DeepMind",
        "techReport": "https://deepmind.google/models/model-cards/gemini-2-5-pro/",
        "contextLength": 1048576,
        "architecture": "gemini",
        "inputModalities": ["text", "image", "audio", "video"],
        "outputModalities": ["text"],
        "releasedAt": "2025-03-25T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Gemini",
    },
    {
        "id": "google/gemini-3-flash",
        "name": "Gemini 3 Flash",
        "provider": "Google DeepMind",
        "techReport": "https://storage.googleapis.com/deepmind-media/Model-Cards/Gemini-3-Flash-Model-Card.pdf",
        "contextLength": 1048576,
        "architecture": "gemini",
        "inputModalities": ["text", "image", "audio", "video"],
        "outputModalities": ["text"],
        "releasedAt": "2025-12-17T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Gemini",
    },
    {
        "id": "google/gemini-3-pro",
        "name": "Gemini 3 Pro",
        "provider": "Google DeepMind",
        "techReport": "https://storage.googleapis.com/deepmind-media/Model-Cards/Gemini-3-Pro-Model-Card.pdf",
        "contextLength": 1048576,
        "architecture": "gemini",
        "inputModalities": ["text", "image", "audio", "video"],
        "outputModalities": ["text"],
        "releasedAt": "2025-12-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Gemini",
    },
    {
        "id": "google/gemini-3.1-flash-lite",
        "name": "Gemini 3.1 Flash-Lite",
        "provider": "Google DeepMind",
        "techReport": "https://deepmind.google/models/model-cards/gemini-3-1-flash-lite/",
        "contextLength": 1048576,
        "architecture": "gemini",
        "inputModalities": ["text", "image", "audio", "video"],
        "outputModalities": ["text"],
        "releasedAt": "2026-03-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Gemini",
    },
    {
        "id": "google/gemini-3.1-flash",
        "name": "Gemini 3.1 Flash",
        "provider": "Google DeepMind",
        "techReport": "https://deepmind.google/models/model-cards/gemini-3-1-flash-audio/",
        "contextLength": 1048576,
        "architecture": "gemini",
        "inputModalities": ["text", "image", "audio", "video"],
        "outputModalities": ["text", "audio"],
        "releasedAt": "2026-02-01T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Gemini",
    },
    {
        "id": "google/gemini-3.1-pro",
        "name": "Gemini 3.1 Pro",
        "provider": "Google DeepMind",
        "techReport": "https://deepmind.google/models/model-cards/gemini-3-1-pro/",
        "contextLength": 1048576,
        "architecture": "gemini",
        "inputModalities": ["text", "image", "audio", "video"],
        "outputModalities": ["text"],
        "releasedAt": "2026-02-19T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "Gemini",
    },

    # ── OpenAI — GPT-4o and o-series ──────────────────────────────────────────
    {
        "id": "openai/gpt-4o",
        "name": "GPT-4o",
        "provider": "OpenAI",
        "contextLength": 128000,
        "architecture": "gpt4",
        "inputModalities": ["text", "image", "audio"],
        "outputModalities": ["text", "audio"],
        "releasedAt": "2024-05-13T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "GPT",
    },
    {
        "id": "openai/gpt-4o-mini",
        "name": "GPT-4o mini",
        "provider": "OpenAI",
        "contextLength": 128000,
        "architecture": "gpt4",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2024-07-18T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "GPT",
    },
    {
        "id": "openai/o1",
        "name": "o1",
        "provider": "OpenAI",
        "contextLength": 200000,
        "architecture": "o1",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2024-09-12T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "o-series",
    },
    {
        "id": "openai/o1-mini",
        "name": "o1-mini",
        "provider": "OpenAI",
        "contextLength": 128000,
        "architecture": "o1",
        "inputModalities": ["text"],
        "outputModalities": ["text"],
        "releasedAt": "2024-09-12T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "o-series",
    },
    {
        "id": "openai/o1-pro",
        "name": "o1-pro",
        "provider": "OpenAI",
        "contextLength": 200000,
        "architecture": "o1",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2024-12-05T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "o-series",
    },
    {
        "id": "openai/o3",
        "name": "o3",
        "provider": "OpenAI",
        "contextLength": 200000,
        "architecture": "o3",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-04-16T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "o-series",
    },
    {
        "id": "openai/o3-pro",
        "name": "o3-pro",
        "provider": "OpenAI",
        "contextLength": 200000,
        "architecture": "o3",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-06-10T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "o-series",
    },
    {
        "id": "openai/gpt-4.1",
        "name": "GPT-4.1",
        "provider": "OpenAI",
        "contextLength": 1047576,
        "architecture": "gpt4",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-04-14T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "GPT",
    },
    {
        "id": "openai/gpt-4.1-mini",
        "name": "GPT-4.1 mini",
        "provider": "OpenAI",
        "contextLength": 1047576,
        "architecture": "gpt4",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-04-14T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "GPT",
    },
    {
        "id": "openai/gpt-4.1-nano",
        "name": "GPT-4.1 nano",
        "provider": "OpenAI",
        "contextLength": 1047576,
        "architecture": "gpt4",
        "inputModalities": ["text", "image"],
        "outputModalities": ["text"],
        "releasedAt": "2025-04-14T00:00:00.000Z",
        "isMoe": False,
        "architectureFamily": "GPT",
    },
]


def main():
    with open(MODELS_FILE, encoding="utf-8") as f:
        models = json.load(f)

    existing_ids = {m["id"] for m in models}
    added = []
    skipped = []

    for entry in NEW_ENTRIES:
        if entry["id"] in existing_ids:
            skipped.append(entry["id"])
        else:
            models.append(entry)
            added.append(entry["id"])

    # Sort by releasedAt then id for stable ordering
    models.sort(key=lambda m: (m.get("releasedAt", ""), m["id"]))

    with open(MODELS_FILE, "w", encoding="utf-8") as f:
        json.dump(models, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"Added {len(added)} models:")
    for mid in added:
        print(f"  + {mid}")
    if skipped:
        print(f"\nSkipped {len(skipped)} already-present:")
        for mid in skipped:
            print(f"  = {mid}")


if __name__ == "__main__":
    main()
